version: '3.8'

services:
  backend:
    image: bloglist-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app
    ports:
      - 3022:3022
    container_name: bloglist-backend
    environment: 
      - MONGODB_URI
      - SECRET
      - TEST_MONGODB_URI
      - PORT

  frontend:
    image: bloglist-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: bloglist-frontend